# Generated by Django 2.1.3 on 2018-12-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0002_auto_20181209_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='form_url',
            field=models.CharField(default='www.ssss.com', max_length=200),
            preserve_default=False,
        ),
    ]
