# Generated by Django 2.1.3 on 2018-12-10 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0003_university_form_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_name', models.CharField(max_length=100)),
                ('self_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userservicesuniversities',
            name='university',
        ),
        migrations.RemoveField(
            model_name='userservicesuniversities',
            name='user',
        ),
        migrations.RemoveField(
            model_name='university',
            name='form_url',
        ),
        migrations.DeleteModel(
            name='UserServicesUniversities',
        ),
    ]
