# Generated by Django 2.1.3 on 2018-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0004_auto_20181210_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.BigIntegerField(default=0, max_length=100),
        ),
    ]
