# Generated by Django 2.1.3 on 2018-12-12 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0005_customuser_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('monday_breakfast', models.CharField(default='-', max_length=100)),
                ('tuesday_breakfast', models.CharField(default='-', max_length=100)),
                ('wednesday_breakfast', models.CharField(default='-', max_length=100)),
                ('thursday_breakfast', models.CharField(default='-', max_length=100)),
                ('friday_breakfast', models.CharField(default='-', max_length=100)),
                ('saturday_breakfast', models.CharField(default='-', max_length=100)),
                ('sunday_breakfast', models.CharField(default='-', max_length=100)),
                ('monday_lunch', models.CharField(default='-', max_length=100)),
                ('tuesday_lunch', models.CharField(default='-', max_length=100)),
                ('wednesday_lunch', models.CharField(default='-', max_length=100)),
                ('thursday_lunch', models.CharField(default='-', max_length=100)),
                ('friday_lunch', models.CharField(default='-', max_length=100)),
                ('saturday_lunch', models.CharField(default='-', max_length=100)),
                ('sunday_lunch', models.CharField(default='-', max_length=100)),
                ('monday_dinner', models.CharField(default='-', max_length=100)),
                ('tuesday_dinner', models.CharField(default='-', max_length=100)),
                ('wednesday_dinner', models.CharField(default='-', max_length=100)),
                ('thursday_dinner', models.CharField(default='-', max_length=100)),
                ('friday_dinner', models.CharField(default='-', max_length=100)),
                ('saturday_dinner', models.CharField(default='-', max_length=100)),
                ('sunday_dinner', models.CharField(default='-', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZorroCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
