# Generated by Django 2.1.3 on 2018-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0006_reservedtable_zorrocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chat_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
