# Generated by Django 2.1.3 on 2018-12-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0007_auto_20181212_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedtable',
            name='credit',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
