# Generated by Django 2.1.3 on 2018-12-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0008_reservedtable_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtable',
            name='credit',
            field=models.FloatField(default=-30),
        ),
    ]
