# Generated by Django 2.1.3 on 2018-12-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0009_auto_20181213_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='reserved_table',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='reserve_table',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='reserve_url',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
