# Generated by Django 2.1.3 on 2019-01-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0012_merchants_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='url_next_week',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservedtable',
            name='week_start_date',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
