# Generated by Django 2.1.3 on 2019-01-01 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0013_auto_20190101_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchants',
            name='is_active',
        ),
    ]
