# Generated by Django 2.1.3 on 2019-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0014_remove_merchants_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='tag',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='zorrocode',
            name='percent',
            field=models.IntegerField(default=100),
        ),
    ]
