# Generated by Django 2.1.3 on 2019-01-21 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0015_auto_20190110_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamadPrefrredDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_sunday_breakfast', models.BooleanField(default=False)),
                ('reserve_monday_breakfast', models.BooleanField(default=False)),
                ('reserve_tuesday_breakfast', models.BooleanField(default=False)),
                ('reserve_wednesday_breakfast', models.BooleanField(default=False)),
                ('reserve_thursday_breakfast', models.BooleanField(default=False)),
                ('reserve_friday_breakfast', models.BooleanField(default=False)),
                ('reserve_saturday_breakfast', models.BooleanField(default=False)),
                ('reserve_sunday_lunch', models.BooleanField(default=False)),
                ('reserve_monday_lunch', models.BooleanField(default=False)),
                ('reserve_tuesday_lunch', models.BooleanField(default=False)),
                ('reserve_wednesday_lunch', models.BooleanField(default=False)),
                ('reserve_thursday_lunch', models.BooleanField(default=False)),
                ('reserve_friday_lunch', models.BooleanField(default=False)),
                ('reserve_saturday_lunch', models.BooleanField(default=False)),
                ('reserve_sunday_dinner', models.BooleanField(default=False)),
                ('reserve_monday_dinner', models.BooleanField(default=False)),
                ('reserve_tuesday_dinner', models.BooleanField(default=False)),
                ('reserve_wednesday_dinner', models.BooleanField(default=False)),
                ('reserve_thursday_dinner', models.BooleanField(default=False)),
                ('reserve_friday_dinner', models.BooleanField(default=False)),
                ('reserve_saturday_dinner', models.BooleanField(default=False)),
                ('active_self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.UserSelfs')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_used',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='friday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='friday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='friday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='monday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='monday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='monday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='saturday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='saturday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='saturday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='sunday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='sunday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='sunday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='thursday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='thursday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='thursday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='tuesday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='tuesday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='tuesday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='wednesday_breakfast_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='wednesday_dinner_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='reservedtable',
            name='wednesday_lunch_self',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='samadprefrreddays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
