# Generated by Django 2.1.3 on 2019-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0016_auto_20190121_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='captcha_url',
            field=models.CharField(default='-', max_length=400),
        ),
        migrations.AddField(
            model_name='zorrocode',
            name='max_time',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='zorrocode',
            name='time_used',
            field=models.IntegerField(default=0),
        ),
    ]
