# Generated by Django 2.1.3 on 2019-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0020_auto_20190205_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurantusers',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
