# Generated by Django 2.1.3 on 2019-02-06 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0021_auto_20190205_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurantusers',
            name='university',
        ),
        migrations.DeleteModel(
            name='FoodRestaurant',
        ),
        migrations.DeleteModel(
            name='FoodUser',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
        migrations.DeleteModel(
            name='RestaurantUsers',
        ),
    ]
