# Generated by Django 2.1.3 on 2019-02-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0022_auto_20190206_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='simple_url',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
