# Generated by Django 2.1.3 on 2019-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantusers',
            name='order_number',
        ),
        migrations.AddField(
            model_name='fooduser',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
