# Generated by Django 2.1.3 on 2019-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_auto_20190206_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='address',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
