# Generated by Django 2.1.3 on 2019-02-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0022_auto_20190206_1402'),
        ('order', '0003_auto_20190206_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(default='0', max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.FoodUser')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePendingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=11)),
                ('chat_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantUniversityCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Restaurant')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.University')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='food',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantusers',
            name='university',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='pay_method',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.RestaurantMenu'),
        ),
        migrations.DeleteModel(
            name='FoodRestaurant',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='RestaurantUsers',
        ),
        migrations.AddField(
            model_name='orderfood',
            name='invoice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Invoice'),
        ),
    ]
