# Generated by Django 2.1.3 on 2019-02-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0004_auto_20190208_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
