# Generated by Django 2.1.3 on 2019-02-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0005_invoice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='food_type',
            field=models.CharField(default='ناهار', max_length=10),
        ),
    ]
