# Generated by Django 2.1.3 on 2019-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0006_restaurantmenu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='food_type',
            field=models.CharField(default='main', max_length=10),
        ),
    ]
